# Spaceship theme with transient prompt
version = 4
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = 'lightYellow'
    template = "\n{{ .UserName }} "

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'cyan'
    template = '<#ffffff>in</> {{ .Path }} '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#ff94df'
    template = "<#ffffff>on</> {{ .HEAD }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "

    [blocks.segments.properties]
      branch_icon = " <#ff94df><b>\ue0a0 </b></>"

  [[blocks.segments]]
    type = 'shell'
    style = 'plain'
    foreground = '#7aa2f7'
    template = "<#ffffff>via</> {{ .Name }} "

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'magenta'
    template = "<#ffffff>took</> {{ .FormattedMs }}"

    [blocks.segments.properties]
      threshold = 500
      style = 'roundrock'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'lightGreen'
    template = "\u276f"

# Transient prompt
[transient_prompt]
  foreground = 'lightGreen'
  template = "\u276f "
