name: Build ZMK Firmware

on:
  push:
    paths:
      - 'zmk/**'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config-path: zmk
